[package]
name = "tree-sitter-mal"
description = "mal grammar for the tree-sitter parsing library"
version = "0.0.1"
keywords = ["incremental", "parsing", "mal"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/sogaiu/tree-sitter-mal"
edition = "2018"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "0.19.3"

[build-dependencies]
cc = "1.0"
